### ISSUE TITLE
Когда бета?

### ISSUE THREAD

**Issue by Arny4** [plash/plash#1]
Жду не дождусь хотябы выхода Bet'ы . Хотелось бы глянуть на код). Да и странно, за месяц разработки в интерфейсе даже кнопки нету. А может кому-то лень просто вылаживать код. Ну а если готовится что-то годное то удачи, Питонист)!
```
def goodbye():
      print("Удачи и пока >:)")

goodbye()
```

**Comment by ketsu8** [comment]
Скорее всего бета выйдет ближе к лету. Релиз планируется примерно в 10-х числах октября. Сейчас низкая активность из-за нехватки времени, и занятости другими проектами.

**Comment by Arny4** [comment]
Можно вопрос. На каком языке написана последняя версия Reserv? И когда уже всётаки будет делан нормально сайт чтобы антивирусы eset не блочили его, добавление в исключения не помогает. Надежда на тебя)

**Comment by ketsu8** [comment]
> Можно вопрос. На каком языке написана последняя версия Reserv? И когда уже всётаки будет доделан нормально сайт чтобы антивирусы eset не блочили его, добавление в исключения не помогает. Надежда на тебя)

ESET блокирует сайт из за того, что отсутствует SSL сертификат. В ближайшее время я надеюсь его получить и исправить ситуацию. Последний Reserv написан на фреймворке .NET с использованием C#. Как написано в описании Plash – после выхода его релизной версии будет выложен исходный код Reserv 2.
