### ISSUE TITLE
Оригинальная иконка

### ISSUE THREAD

**Issue by breitburg** [plash/plash#2]
Мы думаем над своей новой оригинальной иконкой, потому-как мы посчитали что кувшинка из Minecraft – это не очень хорошая идея. Предлагайте свои варианты иконок, или пишите что изменить в имеющихся для достижения лучшего результата.

Вот последний вариант логотипа к которому мы с пришли командой. Высказывайте свои мысли на этот счет.
![Последний вариант](https://user-images.githubusercontent.com/25728414/54070802-f0cbb680-4275-11e9-9236-4fcae1b560a5.png)

**Comment by Arny4** [comment]
Можно попробвать сделать 2д логотип типо [этого](http://prntscr.com/mvg1xv).

**Comment by ketsu8** [comment]
> Можно попробвать сделать 2д логотип типо [этого](http://prntscr.com/mvg1xv).
> Это будет вполне нормально и современно.

Ваше мнение имеет место быть, но я считаю что объемная 3D иконка смотрелась бы лучше и серьезнее. То, что вы отправили в качестве примера, на мой взгляд будет сильно выбиваться из общего стиля интерфейса целевых платформ на которых будет выпущен Plash в сравнении с объемным вариантом.

**Comment by ketsu8** [comment]
Кстати, еще есть вот такой вариант. Что на счет него?
![logo2](https://user-images.githubusercontent.com/25728414/54077121-5e530380-42c5-11e9-8fca-fa17228bd6e1.png)

**Comment by ketsu8** [comment]
Вот кстати рендер для текущего лого.

![plash](https://user-images.githubusercontent.com/25728414/54077520-ab85a400-42ca-11e9-9d48-e0e279490e1e.png)

**Comment by Arny4** [comment]
Нормально, только выдавливание нехватает, и да модель делалась в Cinema 4D ?)

**Comment by Arny4** [comment]
Както-так. В фотошоп ити лень так что вот.
![Rig_Light](https://user-images.githubusercontent.com/43936310/54084438-b16a9c00-4341-11e9-930b-9d6ee372e119.png)

**Comment by ketsu8** [comment]
Выглядит очень круто! Мне понравилась идея. Как на счет моего варианта?

![snap2019-03-10-16-23-23](https://user-images.githubusercontent.com/25728414/54085614-04981b00-4351-11e9-87dd-0fa7b68fadca.png)

**Comment by Arny4** [comment]
Ну внутренняя часть слишком сильно выдавлена. Смотрится так-себе. Ненужно слишком сильно выдавливать одну часть.

**Comment by ketsu8** [comment]
Дизайном и интерфейсом занимаюсь я, но в команде еще несколько человек занимающиеся программной частью.

**Comment by Arny4** [comment]
Когда в вк ваша комманда начнём отвечать? Как-будто я в чс.)
